DROP TABLE IF EXISTS CONFIG_JOB_INFO;

CREATE TABLE CONFIG_JOB_INFO (
    ID VARCHAR(36) PRIMARY KEY,
    JOB_NAME VARCHAR(255) DEFAULT NULL,
    JOB_GROUP VARCHAR(255) DEFAULT NULL,
    JOB_CLASS VARCHAR(255) NOT NULL,
    REPEAT_TIME BIGINT(20) DEFAULT NULL,
    IS_CRON BOOLEAN DEFAULT FALSE,
    CRON_EXPRESSION VARCHAR(255) DEFAULT NULL)
ENGINE=InnoDB;